python -m analyse_vit.rare_colour_bias.flux_sam_composite \
 --pipeline qwen \
 --model-id stabilityai/stable-diffusion-3.5-large \
 --output-dir results \
 --background-prompt "A grass field" \
 --base-prompt-elements-json data/prompt_seeds/kangaroo/real_kangaroo_prompt_seeds.json \
 --paired-prompt-elements-json data/prompt_seeds/kangaroo/paired_kangaroo_prompt_seeds.json \
 --dominant-color "brown" \
 --rare-color "pink" \
 --seed-bg 123 \
 --seed-real 456 \
 --seed-toy 789 \
 --num-inference-steps 30 \
 --guidance-scale 2.5 \
 --target-hue-deg 210 \
 --sam-prompt-mode box \
 --sam-checkpoint models/sam/sam_vit_h_4b8939.pth \
 --num-runs 10 \
