{   ((1, 8192), 0, 'inductor_standalone'): (   'artifact_compile_range_1_8192_subgraph_0',
                                               '/home/akasakam/projects/spatial_reasoning/projects/image_editing/experiments/analyse_vit/.cache/vllm/torch_compile_cache/20ab7cdb27/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_0'),
    ((1, 8192), 1, 'inductor_standalone'): (   'artifact_compile_range_1_8192_subgraph_1',
                                               '/home/akasakam/projects/spatial_reasoning/projects/image_editing/experiments/analyse_vit/.cache/vllm/torch_compile_cache/20ab7cdb27/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_1'),
    ((1, 8192), 2, 'inductor_standalone'): (   'artifact_compile_range_1_8192_subgraph_2',
                                               '/home/akasakam/projects/spatial_reasoning/projects/image_editing/experiments/analyse_vit/.cache/vllm/torch_compile_cache/20ab7cdb27/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_2'),
    ((1, 8192), 3, 'inductor_standalone'): (   'artifact_compile_range_1_8192_subgraph_3',
                                               '/home/akasakam/projects/spatial_reasoning/projects/image_editing/experiments/analyse_vit/.cache/vllm/torch_compile_cache/20ab7cdb27/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_3'),
    ((1, 8192), 4, 'inductor_standalone'): (   'artifact_compile_range_1_8192_subgraph_4',
                                               '/home/akasakam/projects/spatial_reasoning/projects/image_editing/experiments/analyse_vit/.cache/vllm/torch_compile_cache/20ab7cdb27/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_4'),
    ((1, 8192), 5, 'inductor_standalone'): (   'artifact_compile_range_1_8192_subgraph_5',
                                               '/home/akasakam/projects/spatial_reasoning/projects/image_editing/experiments/analyse_vit/.cache/vllm/torch_compile_cache/20ab7cdb27/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_5'),
    ((1, 8192), 6, 'inductor_standalone'): (   'artifact_compile_range_1_8192_subgraph_6',
                                               '/home/akasakam/projects/spatial_reasoning/projects/image_editing/experiments/analyse_vit/.cache/vllm/torch_compile_cache/20ab7cdb27/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_6'),
    ((1, 8192), 7, 'inductor_standalone'): (   'artifact_compile_range_1_8192_subgraph_7',
                                               '/home/akasakam/projects/spatial_reasoning/projects/image_editing/experiments/analyse_vit/.cache/vllm/torch_compile_cache/20ab7cdb27/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_7'),
    ((1, 8192), 8, 'inductor_standalone'): (   'artifact_compile_range_1_8192_subgraph_8',
                                               '/home/akasakam/projects/spatial_reasoning/projects/image_editing/experiments/analyse_vit/.cache/vllm/torch_compile_cache/20ab7cdb27/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_8'),
    ((1, 8192), 9, 'inductor_standalone'): (   'artifact_compile_range_1_8192_subgraph_9',
                                               '/home/akasakam/projects/spatial_reasoning/projects/image_editing/experiments/analyse_vit/.cache/vllm/torch_compile_cache/20ab7cdb27/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_9'),
    ((1, 8192), 10, 'inductor_standalone'): (   'artifact_compile_range_1_8192_subgraph_10',
                                                '/home/akasakam/projects/spatial_reasoning/projects/image_editing/experiments/analyse_vit/.cache/vllm/torch_compile_cache/20ab7cdb27/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_10'),
    ((1, 8192), 11, 'inductor_standalone'): (   'artifact_compile_range_1_8192_subgraph_11',
                                                '/home/akasakam/projects/spatial_reasoning/projects/image_editing/experiments/analyse_vit/.cache/vllm/torch_compile_cache/20ab7cdb27/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_11'),
    ((1, 8192), 12, 'inductor_standalone'): (   'artifact_compile_range_1_8192_subgraph_12',
                                                '/home/akasakam/projects/spatial_reasoning/projects/image_editing/experiments/analyse_vit/.cache/vllm/torch_compile_cache/20ab7cdb27/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_12'),
    ((1, 8192), 13, 'inductor_standalone'): (   'artifact_compile_range_1_8192_subgraph_13',
                                                '/home/akasakam/projects/spatial_reasoning/projects/image_editing/experiments/analyse_vit/.cache/vllm/torch_compile_cache/20ab7cdb27/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_13'),
    ((1, 8192), 14, 'inductor_standalone'): (   'artifact_compile_range_1_8192_subgraph_14',
                                                '/home/akasakam/projects/spatial_reasoning/projects/image_editing/experiments/analyse_vit/.cache/vllm/torch_compile_cache/20ab7cdb27/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_14'),
    ((1, 8192), 15, 'inductor_standalone'): (   'artifact_compile_range_1_8192_subgraph_15',
                                                '/home/akasakam/projects/spatial_reasoning/projects/image_editing/experiments/analyse_vit/.cache/vllm/torch_compile_cache/20ab7cdb27/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_15'),
    ((1, 8192), 16, 'inductor_standalone'): (   'artifact_compile_range_1_8192_subgraph_16',
                                                '/home/akasakam/projects/spatial_reasoning/projects/image_editing/experiments/analyse_vit/.cache/vllm/torch_compile_cache/20ab7cdb27/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_16'),
    ((1, 8192), 17, 'inductor_standalone'): (   'artifact_compile_range_1_8192_subgraph_17',
                                                '/home/akasakam/projects/spatial_reasoning/projects/image_editing/experiments/analyse_vit/.cache/vllm/torch_compile_cache/20ab7cdb27/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_17'),
    ((1, 8192), 18, 'inductor_standalone'): (   'artifact_compile_range_1_8192_subgraph_18',
                                                '/home/akasakam/projects/spatial_reasoning/projects/image_editing/experiments/analyse_vit/.cache/vllm/torch_compile_cache/20ab7cdb27/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_18'),
    ((1, 8192), 19, 'inductor_standalone'): (   'artifact_compile_range_1_8192_subgraph_19',
                                                '/home/akasakam/projects/spatial_reasoning/projects/image_editing/experiments/analyse_vit/.cache/vllm/torch_compile_cache/20ab7cdb27/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_19'),
    ((1, 8192), 20, 'inductor_standalone'): (   'artifact_compile_range_1_8192_subgraph_20',
                                                '/home/akasakam/projects/spatial_reasoning/projects/image_editing/experiments/analyse_vit/.cache/vllm/torch_compile_cache/20ab7cdb27/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_20'),
    ((1, 8192), 21, 'inductor_standalone'): (   'artifact_compile_range_1_8192_subgraph_21',
                                                '/home/akasakam/projects/spatial_reasoning/projects/image_editing/experiments/analyse_vit/.cache/vllm/torch_compile_cache/20ab7cdb27/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_21'),
    ((1, 8192), 22, 'inductor_standalone'): (   'artifact_compile_range_1_8192_subgraph_22',
                                                '/home/akasakam/projects/spatial_reasoning/projects/image_editing/experiments/analyse_vit/.cache/vllm/torch_compile_cache/20ab7cdb27/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_22'),
    ((1, 8192), 23, 'inductor_standalone'): (   'artifact_compile_range_1_8192_subgraph_23',
                                                '/home/akasakam/projects/spatial_reasoning/projects/image_editing/experiments/analyse_vit/.cache/vllm/torch_compile_cache/20ab7cdb27/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_23'),
    ((1, 8192), 24, 'inductor_standalone'): (   'artifact_compile_range_1_8192_subgraph_24',
                                                '/home/akasakam/projects/spatial_reasoning/projects/image_editing/experiments/analyse_vit/.cache/vllm/torch_compile_cache/20ab7cdb27/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_24'),
    ((1, 8192), 25, 'inductor_standalone'): (   'artifact_compile_range_1_8192_subgraph_25',
                                                '/home/akasakam/projects/spatial_reasoning/projects/image_editing/experiments/analyse_vit/.cache/vllm/torch_compile_cache/20ab7cdb27/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_25'),
    ((1, 8192), 26, 'inductor_standalone'): (   'artifact_compile_range_1_8192_subgraph_26',
                                                '/home/akasakam/projects/spatial_reasoning/projects/image_editing/experiments/analyse_vit/.cache/vllm/torch_compile_cache/20ab7cdb27/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_26'),
    ((1, 8192), 27, 'inductor_standalone'): (   'artifact_compile_range_1_8192_subgraph_27',
                                                '/home/akasakam/projects/spatial_reasoning/projects/image_editing/experiments/analyse_vit/.cache/vllm/torch_compile_cache/20ab7cdb27/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_27'),
    ((1, 8192), 28, 'inductor_standalone'): (   'artifact_compile_range_1_8192_subgraph_28',
                                                '/home/akasakam/projects/spatial_reasoning/projects/image_editing/experiments/analyse_vit/.cache/vllm/torch_compile_cache/20ab7cdb27/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_28'),
    ((1, 8192), 29, 'inductor_standalone'): (   'artifact_compile_range_1_8192_subgraph_29',
                                                '/home/akasakam/projects/spatial_reasoning/projects/image_editing/experiments/analyse_vit/.cache/vllm/torch_compile_cache/20ab7cdb27/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_29'),
    ((1, 8192), 30, 'inductor_standalone'): (   'artifact_compile_range_1_8192_subgraph_30',
                                                '/home/akasakam/projects/spatial_reasoning/projects/image_editing/experiments/analyse_vit/.cache/vllm/torch_compile_cache/20ab7cdb27/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_30'),
    ((1, 8192), 31, 'inductor_standalone'): (   'artifact_compile_range_1_8192_subgraph_31',
                                                '/home/akasakam/projects/spatial_reasoning/projects/image_editing/experiments/analyse_vit/.cache/vllm/torch_compile_cache/20ab7cdb27/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_31'),
    ((1, 8192), 32, 'inductor_standalone'): (   'artifact_compile_range_1_8192_subgraph_32',
                                                '/home/akasakam/projects/spatial_reasoning/projects/image_editing/experiments/analyse_vit/.cache/vllm/torch_compile_cache/20ab7cdb27/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_32'),
    ((1, 8192), 33, 'inductor_standalone'): (   'artifact_compile_range_1_8192_subgraph_33',
                                                '/home/akasakam/projects/spatial_reasoning/projects/image_editing/experiments/analyse_vit/.cache/vllm/torch_compile_cache/20ab7cdb27/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_33'),
    ((1, 8192), 34, 'inductor_standalone'): (   'artifact_compile_range_1_8192_subgraph_34',
                                                '/home/akasakam/projects/spatial_reasoning/projects/image_editing/experiments/analyse_vit/.cache/vllm/torch_compile_cache/20ab7cdb27/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_34'),
    ((1, 8192), 35, 'inductor_standalone'): (   'artifact_compile_range_1_8192_subgraph_35',
                                                '/home/akasakam/projects/spatial_reasoning/projects/image_editing/experiments/analyse_vit/.cache/vllm/torch_compile_cache/20ab7cdb27/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_35'),
    ((1, 8192), 36, 'inductor_standalone'): (   'artifact_compile_range_1_8192_subgraph_36',
                                                '/home/akasakam/projects/spatial_reasoning/projects/image_editing/experiments/analyse_vit/.cache/vllm/torch_compile_cache/20ab7cdb27/rank_0_0/backbone/artifact_compile_range_1_8192_subgraph_36')}